// sign in
export const SIGN_IN = 'SIGN_IN'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR'

//sign up
export const SIGN_UP = 'SIGN_UP'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR'

// post 
export const FETCH_POSTS = 'FETCH_POST'
export const FETCH_POSTS_SUCCESS = 'FETCH_POST_SUCCESS'
export const FETCH_POSTS_ERROR = 'FETCH_POST_ERROR'

// add comment 
export const ADD_COMMENT = 'ADD_COMMENT'
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS'
export const ADD_COMMENT_ERROR = 'ADD_COMMENT_ERROR'

// load more comment
export const LOAD_MORE_COMMENT = 'LOAD_MORE_COMMENT'
export const LOAD_MORE_COMMENT_SUCCESS = 'LOAD_MORE_COMMENT_SUCCESS'
export const LOAD_MORE_COMMENT_ERROR = 'LOAD_MORE_COMMENT_ERROR'

// delete comment of post by id
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS'
export const DELETE_COMMENT_ERROR = 'DELETE_COMMENT_ERROR'

// get post by username.
export const GET_POSTS_BY_USERNAME = 'GET_POSTS_BY_USERNAME'
export const GET_POSTS_BY_USERNAME_SUCCESS = 'GET_POSTS_BY_USERNAME_SUCCESS'
export const GET_POSTS_BY_USERNAME_ERROR = 'GET_POSTS_BY_USERNAME_ERROR'

// get public profile
export const GET_USER_PUBLIC_PROFILE = 'GET_USER_PUBLIC_PROFILE'
export const GET_USER_PUBLIC_PROFILE_SUCCESS = 'GET_USER_PUBLIC_PROFILE_SUCCESS'

// get more posts of user
export const GET_MORE_POSTS_BY_USERNAME = 'GET_MORE_POSTS_BY_USERNAME'
export const GET_MORE_POSTS_BY_USERNAME_SUCCESS = 'GET_MORE_POSTS_BY_USERNAME_SUCCESS'

// select post
export const SELECT_CURRENT_POST = 'SELECT_CURRENT_POST'
export const REQUEST_OPEN_MODAL = 'REQUEST_OPEN_MODAL'
export const REQUEST_CLOSE_MODAL = 'REQUEST_CLOSE_MODAL'
export const NEXT_POST = 'NEXT_POST'
export const PREV_POST = 'PRE_POST'

// get more comment of post in profile.
export const LOAD_MORE_COMMENT_PROFILE = 'GET_MORE_COMMENT_PROFILE'
export const LOAD_MORE_COMMENT_PROFILE_SUCCESS = 'GET_MORE_COMMENT_PROFILE_SUCCESS'

export const DELETE_COMMENT_PROFILE = 'DELETE_COMMENT_PROFILE'
export const DELETE_COMMENT_PROFILE_SUCCESS = 'DELETE_COMMENT_PROFILE_SUCCESS'


// add comment profile
export const ADD_COMMENT_PROFILE = 'ADD_COMMENT_PROFILE'
export const ADD_COMMENT_PROFILE_SUCCESS = 'ADD_COMMENT_PROFILE_SUCCESS'

// like and dislike
export const LIKE_POST = 'LIKE_POST'
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS'

export const DISLIKE_POST = 'DISLIKE_POST'
export const DISLIKE_POST_SUCCESS = 'DISLIKE_POST_SUCCESS'

// upload post
export const UPLOAD_POST = 'UPLOAD_POST'
export const UPLOAD_POST_SUCCESS = 'UPLOAD_POST_SUCCESS'

// create post
export const NEXT_STEP_CREATE_POST = 'NEXT_STEP_CREATE_POST'
export const PREV_STEP_CREATE_POST = 'PREV_STEP_CREATE_POST'