// sign in
export const SIGN_IN = 'SIGN_IN'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR'

//sign up
export const SIGN_UP = 'SIGN_UP'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR'

// post 
export const FETCH_POSTS = 'FETCH_POST'
export const FETCH_POSTS_SUCCESS = 'FETCH_POST_SUCCESS'
export const FETCH_POSTS_ERROR = 'FETCH_POST_ERROR'

// add comment 
export const ADD_COMMENT = 'ADD_COMMENT'
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS'
export const ADD_COMMENT_ERROR = 'ADD_COMMENT_ERROR'

// load more comment
export const LOAD_MORE_COMMENT = 'LOAD_MORE_COMMENT'
export const LOAD_MORE_COMMENT_SUCCESS = 'LOAD_MORE_COMMENT_SUCCESS'
export const LOAD_MORE_COMMENT_ERROR = 'LOAD_MORE_COMMENT_ERROR'

// delete comment of post by id
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS'
export const DELETE_COMMENT_ERROR = 'DELETE_COMMENT_ERROR'

// get post by username.
export const GET_POSTS_BY_USERNAME = 'GET_POSTS_BY_USERNAME'
export const GET_POSTS_BY_USERNAME_SUCCESS = 'GET_POSTS_BY_USERNAME_SUCCESS'
export const GET_POSTS_BY_USERNAME_ERROR = 'GET_POSTS_BY_USERNAME_ERROR'