
export const listFilter = [
    {
        label: '_1977',
        brightness: 1.1,
        contrast: 1.1,
        saturate: 1.3,
    },
    {
        label: 'aden',
        hueRotate: -20,
        brightness: 1.2,
        contrast: 0.9,
        saturate: .85,
    },
    {
        label: 'amaro',
        brightness: 1.1,
        contrast: 0.9,
        saturate: 1.5,
    },
    {
        label: 'brannan',
        brightness: 1.0,
        contrast: 1.4,
        sepia: 0.5,
        saturate: 1.0, 
    },
    {
        label: 'brooklyn',
        brightness: 1.1,
        contrast: 0.9,
        saturate: 1.0,
    },
    {
        label: 'clarendon',
        brightness: 1.0,
        contrast: 1.2,
        saturate: 1.35,
    },
    {
        label: 'earlybird',
        brightness: 1.0,
        contrast: 0.9,
        saturate: 1.0,
        sepia: 0.2,
    },
    {
        label: 'gingham',
        brightness: 1.05,
        contrast: 1.0,
        hueRotate: -10,
        saturate: 1.0,
    },
    {
        label: 'hudson',
        brightness: 1.2,
        contrast: 0.9,
        saturate: 1.1,
    },
    {
        label: 'inkwell',
        brightness: 1.1,
        contrast: 1.1,
        sepia: 0.3,
        saturate: 1.0,
        grayscale: 1,
    },
    {
        label: 'lark',
        brightness: 1.0,
        contrast: 0.9,
        saturate: 1.0,
    },
    {
        label: 'lofi',
        brightness: 1.0,
        contrast: 1.5,
        saturate: 1.1,
    },
    {
        label: 'mayfair',
        brightness: 1.0,
        contrast: 1.1,
        saturate: 1.1,
    },
    {
        label: 'moon',
        brightness: 1.1,
        contrast: 1.1,
        saturate: 1.0,
        grayscale: 1,
    },
    {
        label: 'nashville',
        brightness: 1.05,
        contrast: 1.2,
        saturate: 1.2,
        sepia: 0.2,
    },
    {
        label: 'perpetua',
        brightness: 1.0,
        contrast: 1.0,
        saturate: 1.0,
    },
    {
        label: 'reyes',
        brightness: 1.1,
        contrast: 0.85,
        saturate: 0.75,
        sepia: 0.22,
    },
    {
        label: 'rise',
        brightness: 1.05,
        contrast: 0.9,
        saturate: 0.9,
        sepia: 0.2,
    },
    {
        label: 'slumber',
        brightness: 1.05,
        contrast: 1.0,
        saturate: 0.66,
    },
    {
        label: 'toaster',
        brightness: 0.9,
        contrast: 1.5,
        saturate: 1.0,
    },
    {
        label: 'walden',
        brightness: 1.1,
        hueRotate: -10,
        contrast: 1.0,
        sepia: 0.3,
        saturate: 1.6,
    },
    // {
    //     label: 'willow',
    //     brightness: 0.9,
    //     contrast: 0.95,
    //     saturate: 1.0,
    //     grayscale: 0.5,
    // },
    // {
    //     label: 'xpro2',
    //     brightness: 1.0,
    //     contrast: 1.0,
    //     saturate: 1.0,
    //     sepia: 0.3,
    // }
]
